# Generated by Django 2.2 on 2020-02-28 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='uploadByURL',
            field=models.URLField(default=django.utils.timezone.now, max_length=350),
            preserve_default=False,
        ),
    ]
