# Generated by Django 2.2 on 2020-02-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0002_uploadmodel_uploadbyurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='uploadedFile',
            field=models.FileField(blank=True, upload_to='uploadedFiles/%Y/%m/%d/'),
        ),
    ]
