# Generated by Django 2.2 on 2020-03-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0003_auto_20200228_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='uploadByURL',
        ),
    ]
