# Generated by Django 2.2 on 2020-03-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0004_remove_uploadmodel_uploadbyurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='uploadedFile',
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='uploadDateURL',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='uploadFileName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
