# Generated by Django 2.2 on 2020-03-06 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0005_auto_20200305_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadmodel',
            old_name='uploadFileName',
            new_name='secondFileName',
        ),
        migrations.RemoveField(
            model_name='uploadmodel',
            name='uploadDateURL',
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='firstFileName',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='uploadFileFirst',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='uploadFileSecond',
            field=models.TextField(blank=True),
        ),
    ]
