# Generated by Django 2.2 on 2020-03-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0007_auto_20200306_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadmodel',
            old_name='firstFileName',
            new_name='fileNames',
        ),
        migrations.RenameField(
            model_name='uploadmodel',
            old_name='uploadFileFirst',
            new_name='uploadedFiles',
        ),
        migrations.RemoveField(
            model_name='uploadmodel',
            name='secondFileName',
        ),
        migrations.RemoveField(
            model_name='uploadmodel',
            name='uploadFileSecond',
        ),
    ]
