# Generated by Django 2.2 on 2020-03-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0010_auto_20200310_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='uploadedFiles',
            field=models.FileField(upload_to=''),
        ),
    ]
