# Generated by Django 2.2 on 2020-03-16 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0013_auto_20200315_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadURLmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadURL', models.TextField()),
                ('fileFromURL', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fileconverter.UploadModel')),
            ],
        ),
    ]
