# Generated by Django 2.2 on 2020-03-16 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0014_uploadurlmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='uploadByURL',
        ),
    ]
