# Generated by Django 3.0.4 on 2020-03-17 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0015_remove_uploadmodel_uploadbyurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadurlmodel',
            name='fileFromURL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fileconverter.UploadModel'),
        ),
    ]
