# Generated by Django 3.0.4 on 2020-03-18 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0016_auto_20200317_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadurlmodel',
            name='fileFromURL',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='fileconverter.UploadModel'),
            preserve_default=False,
        ),
    ]
