# Generated by Django 3.0.4 on 2020-03-18 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0018_auto_20200318_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadurlmodel',
            name='fileFromURL',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileconverter.UploadModel'),
        ),
    ]
