# Generated by Django 3.0.4 on 2020-03-18 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0021_auto_20200318_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadurlmodel',
            name='uploadURL',
            field=models.URLField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
