# Generated by Django 3.0.4 on 2020-03-18 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0022_auto_20200318_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadurlmodel',
            name='fileFromURL',
            field=models.FileField(blank=True, default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadurlmodel',
            name='uploadURL',
            field=models.URLField(),
        ),
    ]
