# Generated by Django 3.0.4 on 2020-03-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0023_auto_20200318_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckFileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkType', models.BooleanField()),
            ],
        ),
    ]
