# Generated by Django 3.0.4 on 2020-04-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0026_auto_20200407_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckFileType',
        ),
    ]
