# Generated by Django 3.0.4 on 2020-04-22 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0027_delete_checkfiletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='fps_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadurlmodel',
            name='url_fps_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
