# Generated by Django 3.0.4 on 2020-04-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0028_auto_20200422_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='fps_value',
        ),
        migrations.RemoveField(
            model_name='uploadurlmodel',
            name='url_fps_value',
        ),
    ]
