# Generated by Django 3.0.4 on 2020-04-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0031_auto_20200422_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='fps_value',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='uploadurlmodel',
            name='fps_value',
            field=models.IntegerField(default=15),
        ),
    ]
