# Generated by Django 3.0.4 on 2020-04-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0033_auto_20200422_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='fps_value',
        ),
        migrations.RemoveField(
            model_name='uploadurlmodel',
            name='fps_value',
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='fps_values',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadurlmodel',
            name='url_fps_values',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
