# Generated by Django 3.0.4 on 2020-04-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0034_auto_20200422_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='fps_values',
        ),
        migrations.RemoveField(
            model_name='uploadurlmodel',
            name='url_fps_values',
        ),
    ]
