# Generated by Django 3.0.4 on 2020-04-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0036_auto_20200422_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='fps_value',
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='fps_value_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='fps_value_2',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
