# Generated by Django 3.0.4 on 2020-04-23 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0037_auto_20200423_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadurlmodel',
            name='url_fps_value',
        ),
    ]
