# Generated by Django 3.0.4 on 2020-05-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0038_remove_uploadurlmodel_url_fps_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='scaleValue_select_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='scaleValue_select_2',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
