# Generated by Django 3.0.4 on 2020-05-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0040_auto_20200519_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='fps_value_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
