# Generated by Django 3.0.4 on 2020-05-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0043_auto_20200520_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadurlmodel',
            name='URL_fps_value',
        ),
        migrations.RemoveField(
            model_name='uploadurlmodel',
            name='URL_scaleValue_select',
        ),
    ]
