# Generated by Django 3.0.4 on 2020-05-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0044_auto_20200523_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadurlmodel',
            name='URL_fps_value',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadurlmodel',
            name='URL_scaleValue_select',
            field=models.CharField(default=15, max_length=20),
            preserve_default=False,
        ),
    ]
