# Generated by Django 3.0.4 on 2020-05-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0045_auto_20200523_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadurlmodel',
            name='URL_end',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadurlmodel',
            name='URL_start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
