# Generated by Django 3.0.4 on 2020-05-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0046_auto_20200526_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='end_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='end_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='start_1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='start_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
