# Generated by Django 3.0.4 on 2020-06-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0047_auto_20200528_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='end_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='end_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='start_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='start_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadurlmodel',
            name='URL_end',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uploadurlmodel',
            name='URL_start',
            field=models.FloatField(),
        ),
    ]
