# Generated by Django 3.0.4 on 2020-07-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0048_auto_20200603_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadurlmodel',
            name='URL_end_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadurlmodel',
            name='URL_fps_value_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadurlmodel',
            name='URL_scaleValue_select_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uploadurlmodel',
            name='URL_start_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadurlmodel',
            name='fileFromURL_2',
            field=models.FileField(blank=True, upload_to='urlmedia/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='uploadurlmodel',
            name='uploadURL_2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
