# Generated by Django 3.0.4 on 2020-07-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileconverter', '0049_auto_20200723_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadurlmodel',
            name='fileFromURL',
        ),
        migrations.RemoveField(
            model_name='uploadurlmodel',
            name='fileFromURL_2',
        ),
    ]
